namespace ZdAdoConnectorMvc.Models
{
    internal class AdoWorkItemFields
    {
        readonly string[] fields = {
            "Accepted By",
            "Accepted Date",
            "Activated By",
            "Activated Date",
            "Activity Date",
            "Activity",
            "Application Launch Instructions",
            "Application Start Information",
            "Application Type",
            "Area Path",
            "Assigned To",
            "Associated Context Code",
            "Associated Context Owner",
            "Associated Context Type",
            "Associated Context",
            "Attached File Count",
            "Authorized As",
            "Authorized Date",
            "Automated Test Id",
            "Automated Test Name",
            "Automated Test Storage",
            "Automated Test Type",
            "Automation status",
            "Board Column Done",
            "Board Column",
            "Board Lane",
            "Changed By",
            "Changed Date",
            "Closed By",
            "Closed Date",
            "Closed Status Code",
            "Closed Status",
            "Closing Comment",
            "Comment Count",
            "Completed Work",
            "Created By",
            "Created Date",
            "Description",
            "Effort",
            "External Link Count",
            "Finish Date",
            "History",
            "Hyperlink Count",
            "ID",
            "Integration Build",
            "Issue",
            "Iteration Path",
            "Local Data Source",
            "Node Name",
            "Parameters",
            "Priority",
            "Query Text",
            "Rating",
            "Reason",
            "Related Link Count",
            "Remaining Work",
            "Remote Link Count",
            "Rev",
            "Reviewed By",
            "Revised Date",
            "Stack Rank",
            "Start Date",
            "State Change Date",
            "State Code",
            "State",
            "Steps",
            "System Info",
            "Tags",
            "Target Date",
            "Team Project",
            "Test Suite Audit",
            "Test Suite Type Id",
            "Test Suite Type",
            "Title",
            "Watermark",
            "Work Item Type"
        };
    }
}
