// <auto-generated />
namespace Payments_Net462.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Categories_Bmo_Old : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Categories_Bmo_Old));
        
        string IMigrationMetadata.Id
        {
            get { return "201903140719341_Categories_Bmo_Old"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
